### ISSUE TITLE
Do we need to stop() the subscription?

### ISSUE THREAD

**Issue by awei01** [SachaG/smartquery#11]
Just wondering, is there a potential for memory leaking? This is probably more a question as to how the meteor core works, but if we continue `Meteor.subscribe()` from within a helper method, when that helper method is invalided what happens to the previous subscription? Do they just pile up in browser memory?

**Comment by awei01** [comment]
Nevermind. I think it's' answered here: http://docs.meteor.com/#/full/meteor_subscribe

```
If you call Meteor.subscribe within a reactive computation, for example using Tracker.autorun, the subscription will automatically be cancelled when the computation is invalidated or stopped; it's not necessary to call stop on subscriptions made from inside autorun. However, if the next iteration of your run function subscribes to the same record set (same name and parameters), Meteor is smart enough to skip a wasteful unsubscribe/resubscribe. 
```

**Comment by SachaG** [comment]
If I'm not mistaken (but I'd have to test it again to be 100% sure), that's actually kind of a problem because when someone clicks "load more" the subscription is torn down and then recreated (which means there's a split second where the content disappears). So it's definitely an area that needs to be improved.

**Comment by awei01** [comment]
I was more concerned with spinning up more and more subscriptions. But the docs inform me otherwise. 

To address your point, though, isn't that the point of returning an object with access to `subscription.ready()`, to handle loading subscriptions?

**Comment by SachaG** [comment]
Actually never mind, that doesn't happen after all.
