### ISSUE TITLE
[FR] Allow functions that return arrays for `fields` rule

### ISSUE THREAD

**Issue by serkandurusoy** [SachaG/smartquery#2]
If you allow functions, it would be further possible to create fine grained rules that reveal subsets of documents.

For example, we may allow:
- everyone to subscribe to all users' user names,
- admins to subscribe to emails as well
- current user to subscribe to the complete user document

**Comment by SachaG** [comment]
Good point, the current version is probably overthinking it. It'll be easier (and more flexible) to just pass functions for both the fields and filter rules.

**Comment by serkandurusoy** [comment]
Great :)

**Comment by SachaG** [comment]
Done :)

**Comment by serkandurusoy** [comment]
:clap:
