### ISSUE TITLE
Problem with unlimitedOptions? 

### ISSUE THREAD

**Issue by awei01** [SachaG/smartquery#4]
In the following lines: https://github.com/SachaG/smartquery/blob/master/lib/publications.js#L62-L64

Shouldn't the `limit` be deleted instead of `options` like:

```
var unlimitedOptions = _.clone(options);
delete unlimitedOptions.limit;
Counts.publish(this, id, collection.find(validSelector, unlimitedOptions));
```

Then again, couldn't it be simplified like this:

```
Counts.publish(this, id, collection.find(validSelector));
```

**Comment by SachaG** [comment]
I think you're right, I wanted to keep the options but just delete the `limit`.
