### ISSUE TITLE
SmartQuery.create() using cursor having a .sort creates invalid sort object

### ISSUE THREAD

**Issue by awei01** [SachaG/smartquery#7]
If I pass a `sort` option to my cursor like this:

```
SmartQuery.create('foo', Foos.find({}, { sort: { bar: 1 } });
```

I get `Exception from sub SmartQuery_Clients id NTTPFDu8hgvKQQxiy MongoError: Can't canonicalize query: BadValue bad sort specification`.

This line `if (cursor.sorter !== null) { options.sort = cursor.sorter; }` converts the sort option into `MiniMongo.Sorter` object which is unusable on the server side.

**Comment by SachaG** [comment]
Good catch, I guess I'll add a `convertSorter()` function then (unless there's one in Meteor I can access?)

**Comment by SachaG** [comment]
OK, how about now?

**Comment by awei01** [comment]
Works. Thanks.
