### ISSUE TITLE
Handling single record?

### ISSUE THREAD

**Issue by awei01** [SachaG/smartquery#9]
Not sure if this is out of the scope of the package, but how would you handle getting single documents? It doesn't make sense to return the entire object from `SmartQuery.create` that contains helpers like `hasMore`, `count`, etc.

**Comment by SachaG** [comment]
I'm not sure… you could argue it's simpler to have the same API no matter how many documents are returned by the cursor?

**Comment by awei01** [comment]
fair point. your solution seems better.
